version: '3.4' 

services:   

  mariadb: 
    container_name: ExpensesMariaDB 
    image: mariadb 
    volumes:             
      - db_data:/var/lib/mysql
    ports: 
      - "3306:3306" 
    restart: always 
    environment: 
        MYSQL_ROOT_PASSWORD: root 
        MYSQL_DATABASE: UserManagementDB 
  
  usermanagement.api: 
    image: usermanagementapi 
    container_name: UserManagement_API 
    environment:
      - ConnectionString=server=mariadb;port=3306;database=UserManagementDB;uid=root;pwd=root;Convert Zero Datetime=True;sslmode=none
    links: 
          - mariadb:mariadb 
    depends_on: 
            - mariadb 
    ports: 
      - "5001:80" 
    restart: always 
    build: 
      context: ./Back
      dockerfile: ./User.API/Dockerfile  
  
volumes: 
    db_data:  
