version: '3.8' 
volumes: 
    db_data:  
networks:
  atlas_default:
    name: atlas_default
    external: false


services:   

  mariadb: 
    container_name: ExpensesMariaDB 
    image: mariadb 
    volumes:             
      - db_data:/var/lib/mysql
    ports: 
      - "3306:3306" 
    restart: always 
    environment: 
        MYSQL_ROOT_PASSWORD: root 
        MYSQL_DATABASE: UserManagementDB 
  
  usermanagement.api: 
    image: usermanagementapi 
    container_name: UserManagement_API 
    environment:
      - ConnectionString=server=mariadb;port=3306;database=UserManagementDB;uid=root;pwd=root;Convert Zero Datetime=True;sslmode=none
    links: 
          - mariadb:mariadb 
    depends_on: 
            - mariadb 
    ports: 
      - "9001:80" 
    restart: always 
    build: 
      context: ./Back
      dockerfile: ./User.API/Dockerfile  

  expensemanagement.api: 
    image: expensemanagementapi 
    container_name: ExpenseManagement_API 
    environment:
      - ConnectionString=server=mariadb;port=3306;database=ExpenseManagementDB;uid=root;pwd=root;Convert Zero Datetime=True;sslmode=none
    links: 
          - mariadb:mariadb 
    depends_on: 
            - mariadb 
    ports: 
      - "9002:80" 
    restart: always 
    build: 
      context: ./Back
      dockerfile: ./Expense.API/Dockerfile
