version: '3.4'

services:

  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usermanagementdb
    ports:
      - "3308:3306"

  usermanagement.api:
    image: usermanagementapi
    container_name: UserManagement_API    
    environment:
      - ConnectionString=server=127.0.0.1;port=3308;database=expensesmanagementdb;uid=root;pwd=root;Convert Zero Datetime=True;sslmode=none
    links: 
          - mysql:mysql     
    depends_on:
      - mysql
    ports:
      - "5001:80"
    restart: always 
    build:
      context: ./Back
      dockerfile: ./User.API/Dockerfile

  expensesmanagement.api:
    image: expensesmanagementapi
    container_name: ExpensesManagement_API    
    environment:
      - ConnectionString=server=127.0.0.1;port=3308;database=expensesmanagementdb;uid=root;pwd=root;Convert Zero Datetime=True;sslmode=none
    links: 
          - mysql:mysql     
    depends_on:
      - mysql
    ports:
      - "5002:80"
    restart: always 
    build:
      context: ./Back
      dockerfile: ./Expense.API/Dockerfile

  