// <auto-generated />
using System;
using ExpenseManagement.Domain.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseManagement.Domain.Infraestructure.Migrations
{
    [DbContext(typeof(ExpenseManagementContext))]
    [Migration("20200711215031_addStatusAndRecurrenceTypesToExpense")]
    partial class addStatusAndRecurrenceTypesToExpense
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpenseManagement.Domain.Model.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<DateTime>("DatePaidOut")
                        .HasColumnName("datepaidout");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnName("expirationdate");

                    b.Property<int>("IdExpenseRecurrenceType")
                        .HasColumnName("idexpenserecurrencetype");

                    b.Property<int>("IdExpenseStatus")
                        .HasColumnName("idexpensestatus");

                    b.Property<int>("IdExpenseType")
                        .HasColumnName("idexpensetype");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.Property<bool>("PaidOut")
                        .HasColumnName("paidout");

                    b.Property<string>("UserNameOwner")
                        .HasColumnName("usernameowner");

                    b.Property<double>("Value")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("ExpenseManagement.Domain.Model.ExpenseRecurrenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("expensesRecurrenceType");
                });

            modelBuilder.Entity("ExpenseManagement.Domain.Model.ExpenseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("expensesStatus");
                });

            modelBuilder.Entity("ExpenseManagement.Domain.Model.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("expensesType");
                });
#pragma warning restore 612, 618
        }
    }
}
