// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Domain.Infraestructure;

namespace UserManagement.Domain.Infraestructure.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20200711180241_addLastName")]
    partial class addLastName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserManagement.Domain.Model.User", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname");

                    b.Property<Guid>("Id")
                        .HasColumnName("id");

                    b.Property<int>("IdentityDocument")
                        .HasColumnName("identitydocument");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnName("identitynumber");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password");

                    b.Property<string>("SecondEmail")
                        .HasColumnName("secondemail");

                    b.Property<string>("SecondName")
                        .HasColumnName("secondname");

                    b.HasKey("UserName");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
